In [2]:
from numpy import *
a=logspace(1,3,5)
print(a[0])
print(a[1])

10.0
31.622776601683793


In [3]:
for el in a:
    print(el)

10.0
31.622776601683793
100.0
316.22776601683796
1000.0


In [4]:
from numpy import *
a=logspace(1,3,5)
n=len(a)
i=0
while i<n:
    print(a[i])
    i+=1

10.0
31.622776601683793
100.0
316.22776601683796
1000.0


In [8]:
a=arange(1,10,2)
a

array([1, 3, 5])

In [10]:
for el in a:
    print(el)

1
3
5


In [13]:
a=ones(5)
a

array([1., 1., 1., 1., 1.])

In [14]:
a=array([101,102,103,104,105])
a=a+5
a

array([106, 107, 108, 109, 110])

In [16]:
a=array([101,102,104,106,107])
b=array([102,1021,102,102,1016])
c=a+b
c

array([ 203, 1123,  206,  208, 1123])

In [18]:
for eel in a:
    print(eel)

101
102
104
106
107


In [27]:
a=array([100,2,300,4,500])
b=array([100,20,30,400,50])
result=where(a>b,a,b)
result

array([100,  20, 300, 400, 500])

In [36]:
a=array([100,2,300,4,500,0])
b=a
print(id(b))
print(id(a))


1544763083632
1544763083632


In [30]:
b=a.view()
a[1]=80
b[2]=50
a

array([100,  80,  50,   4, 500,   0])

In [31]:
b

array([100,  80,  50,   4, 500,   0])

In [32]:
id(a)

1544763280240

In [33]:
id(b)

1544757871024

In [37]:
print(id(b))
print(id(a))


1544763083632
1544763083632


In [39]:
b=copy(a)
print(id(b))
print(id(a))

1544763355472
1544763083632


n=int(input("enter number of elments"))
a=zeros(n)
for i in range(n):
    u=int(input("enter elements"))
    a[i]=u
a

In [46]:
from numpy import*
n=int(input("enter number of elments"))
a=zeros(n,dtype(int))
for i in range(len(a)):
    x=int(input("enter elemnts"))
    a[i]=x
for i in range(len(a)):
    print(a[i])

enter number of elments5
enter elemnts1
enter elemnts2
enter elemnts3
enter elemnts4
enter elemnts5
1
2
3
4
5


In [51]:
from numpy import *
n=int(input("enter number of elements"))
a=zeros(n)
x=len(a)
i=0
j=0
while i<x:
    m=int(input("enter elements"))
    a[i]=m
    i+=1
print(a)
while j<x:
    print(a[j])
    j+=1
print(a)

enter number of elements5
enter elements1
enter elements2
enter elements3
enter elements4
enter elements5
[1. 2. 3. 4. 5.]
1.0
2.0
3.0
4.0
5.0
[1. 2. 3. 4. 5.]


In [54]:
from numpy import *
a=array([[10,20,30,40],
       [50,60,70,80]])
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

10
20
30
40
50
60
70
80


In [56]:
a[1][3]=800
print(a[1][3])

800


In [57]:
for r in a:
    for c in r:
        print(c)

10
20
30
40
50
60
70
800


In [60]:
n=len(a)
for i in range(n):
    for c in range(len(a[i])):
          print(a[i][c])

10
20
30
40
50
60
70
800


In [61]:
i=0
while i<n:
    j=0
    while j<len(a[i]):
        print(a[i][j])
        j+=1
    i+=1

10
20
30
40
50
60
70
800


In [64]:
a=zeros((3,2))
print(a[0][0])
print(a[0][1])
print(a[1][0])
print(a[1][1])
print(a[2][0])
print(a[2][1])

0.0
0.0
0.0
0.0
0.0
0.0


In [65]:
for r in a:
    for c in a:
        print(c)

[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]


In [68]:
n=len(a)
for i in range(n):
    for j in range(len(a[i])):
        print("index",i,j,a[i][j])

index 0 0 0.0
index 0 1 0.0
index 1 0 0.0
index 1 1 0.0
index 2 0 0.0
index 2 1 0.0


In [69]:
i=0
while i<n:
    j=0
    while j<len(a[i]):
        print("index",i,j,"=",a[i][j])
        j+=1
    i+=1

index 0 0 = 0.0
index 0 1 = 0.0
index 1 0 = 0.0
index 1 1 = 0.0
index 2 0 = 0.0
index 2 1 = 0.0


In [72]:
a=array([1,2,3,4,5,6,7,9,8,10,11,12])
b=reshape(a,(2,3,2))

In [73]:
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  9],
        [ 8, 10],
        [11, 12]]])

In [75]:
a=array([[1,2,3],[4,5,6]])
b=reshape(a,6)
b

array([1, 2, 3, 4, 5, 6])

In [77]:
from numpy import *
e=array([[1,2,3],[4,5,6]])
f=e.flatten()
f

array([1, 2, 3, 4, 5, 6])

from numpy import *
m=int(input("enter number of elemnts"))
n=int(input("enter number of elemnts"))
a=zeros((m,n))
x=len(a)
for i in range(x):
    for j in range(len(a[i])):
        u=int(input("enter elements"))
        a[i][j]=u
for i in range(u):
    for j in range(len(a[i])):
        print(a[i][j])
print(a)

In [80]:
from numpy import *
m=int(input("enter number of elemnts"))
n=int(input("enter number of elemnts"))
a=zeros((m,n))
x=len(a)
for i in range(x):
    for j in range(len(a[i])):
        u=int(input("enter elements"))
        a[i][j]=u
for i in range(x):
    for j in range(len(a[i])):
        print(a[i][j])
print(a)

enter number of elemnts2
enter number of elemnts3
enter elements1
enter elements2
enter elements3
enter elements4
enter elements5
enter elements6
1.0
2.0
3.0
4.0
5.0
6.0
[[1. 2. 3.]
 [4. 5. 6.]]


In [83]:
i=0
while i<x:
    j=0
    while j<len(a[i]):
        x=int(input("enter elements:"))
        a[i][j]=x
        j+=1
    i+=1
while i<x:
    j=0
    while j<len(a[i]):
        print("index",i,j,"=",a[i][j])
        j+=1
    i+=1
print(a)

enter elements:2
enter elements:3
enter elements:1
[[2. 3. 1.]
 [4. 5. 6.]]
