In [1]:
from numpy import *

In [3]:
n=array([[10,20,30],
       [40,50,60],
       [70,80,90]])
print("original array")
print(n[0])


original array
[10 20 30]


In [4]:
print(n[1])

[40 50 60]


In [5]:
a=n[0:]

In [6]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
a=n[1,:]
a

array([40, 50, 60])

In [8]:
a=n[2,:]

In [9]:
a

array([70, 80, 90])

In [10]:
a=n[:0:1,0:1]

In [11]:
a

array([], shape=(0, 1), dtype=int32)

In [13]:
a=[:2:3,2:3]
a

SyntaxError: invalid syntax (<ipython-input-13-299175affaf7>, line 1)

In [20]:
a=([[1:2,1:4]])
a

SyntaxError: invalid syntax (<ipython-input-20-b145a662286f>, line 1)

In [ ]:
a=array([101,102])